[build]
  base = "employess-poll"
  command = "npm run build"
  publish = "employees-poll/build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
